# -*- coding: utf-8 -*-
"""DDPM_jax_implementation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10CMj88nJqf0gxezlThSCSsauSHDTw-oo
"""

import jax
import jax.numpy as jnp
from flax import linen as nn
from typing import Callable
import optax
from google.colab import drive
drive.mount('/content/drive/')
!pip install tensorflow
import tensorflow as tf
import numpy as np
import os
import functools
from tqdm import tqdm
from IPython.display import Image, display, clear_output
import matplotlib.pyplot as plt

tf.config.experimental.set_visible_devices([], 'GPU')
print(jax.devices())

"""# Implementing a DDPM model

## Infrastructure needed

### 1. Forward pass noiser
> - scheduling of $\beta$ parameters + interpolation using $\alpha$ to jump to noised step


### 2. Backward pass denoiser
> - Predict denoising level step
> -


### 3. Architecture
- Implement U-net from Pixel CNN paper.
"""

# Defining the resnet
class DDPMResnet(nn.Module):

    filters: int = 160
    dropout_p: float = 0.5
    @nn.compact
    def __call__(self, x, time_embed, train=True):

        residual = x

        h = nn.GroupNorm(8)(x)
        h = jax.nn.silu(h)
        h = nn.Conv(features=self.filters, kernel_size = (3, 3), padding = 'CIRCULAR')(h)

        # Time embedding
        t = nn.Dense(self.filters)(jax.nn.silu(time_embed))
        h = h + t[:, None, None, :]

        h = nn.GroupNorm(8)(h)
        h = jax.nn.silu(h)
        h_dropout = nn.Dropout(rate = self.dropout_p)(h, deterministic = not train)
        h = nn.Conv(features = self.filters, kernel_size = (3, 3), padding = 'CIRCULAR')(h_dropout)

        if x.shape[-1] != self.filters:
            residual = nn.Conv(self.filters, (1,1), padding = 'CIRCULAR')(residual)

        return h +  residual

# Defining the time embedding

def sinusoidal_time_embedding(t, dim, max_period=10000):
    # t -> (B,), freqs -> (half,)
    half = dim // 2
    freqs = jnp.exp(-jnp.log(max_period) * jnp.arange(half)/ half)

    # project t -> (B, 1), freqs -> (1, half)
    args = t[:, None] * freqs[None, :] # (B, half)
    return jnp.concatenate([jnp.sin(args), jnp.cos(args)], axis = -1)

class SelfAttention(nn.Module):
    num_groups: int = 32
    @nn.compact
    def __call__(self, x):
        B, H, W, C = x.shape # B, 16, 16, 160
        h = nn.GroupNorm(self.num_groups)(x)
        h_flat = h.reshape(B, H*W, C) # B, 256, 160

        # weight matrix is 160x160,
        q = nn.Dense(C)(h_flat) # B, 256, 160 with 160 being the features (channels)
        k = nn.Dense(C)(h_flat)
        v = nn.Dense(C)(h_flat)

        scaling = jnp.sqrt(C)
        attn = jax.nn.softmax(q @ k.transpose(0,2,1) / scaling, axis=-1)
        out = attn @ v

        out = nn.Dense(C)(out)
        out = out.reshape(B, H, W, C)

        return out + x

class Unet(nn.Module):

  # enurate args
  ch: int = 64
  ch_mult: tuple = (1, 1, 1, 2)
  out_ch: int = 3
  in_ch: int = 3

  n_resnet_blocks: int = 1
  dropout_p: float = 0.0
  freq_dim: int = 128
  train = True


  @ nn.compact
  def __call__(self, x, t, train=True):
      ch = self.ch
      temp_ch = ch*4
      num_resolutions = len(self.ch_mult)
      in_ch_mult = (1,) + self.ch_mult

      time_embed = sinusoidal_time_embedding(t, dim=self.freq_dim)
      time_embed = nn.Dense(temp_ch)(time_embed)
      time_embed = jax.nn.silu(time_embed)
      time_embed = nn.Dense(temp_ch)(time_embed)

      h = nn.Conv(ch, kernel_size=(3, 3), padding='CIRCULAR')(x)
      hs = [h]

      # First Resnet block assembly - dim 256x256, 64 filters
      for _ in range(self.n_resnet_blocks):
          h = DDPMResnet(ch*self.ch_mult[0], self.dropout_p)(h, time_embed=time_embed,train=train)
          hs.append(h)

      # Downsampling to 128x128
      h = nn.Conv(ch*self.ch_mult[0], kernel_size=(3, 3), strides=(2, 2), padding=((0,1),(0,1)))(h)
      hs.append(h)

      # Second Resnet block assembly - dim 128x128, 64 filters
      for _ in range(self.n_resnet_blocks):

          h = DDPMResnet(ch*self.ch_mult[1], self.dropout_p)(h, time_embed=time_embed, train=train)
          hs.append(h)

      # Downsampling to 64x64
      h = nn.Conv(ch*self.ch_mult[1], kernel_size=(3, 3), strides=(2, 2), padding=((0,1),(0,1)))(h)
      hs.append(h)

      # Third Resnet block assmebly - dim 64x64, 64 filters
      for _ in range(self.n_resnet_blocks):
          h = DDPMResnet(ch*self.ch_mult[2], self.dropout_p)(h, time_embed=time_embed, train=train)
          hs.append(h)

      # Downsampling to 32x32
      h = nn.Conv(ch*self.ch_mult[2], kernel_size=(3, 3), strides=(2, 2), padding=((0,1),(0,1)))(h)
      hs.append(h)

      # Third Resnet block assmebly - dim 32x32, 128 filters
      for _ in range(self.n_resnet_blocks):
          h = DDPMResnet(ch*self.ch_mult[3], self.dropout_p)(h, time_embed=time_embed, train=train)
          hs.append(h)


      # bottleneck at 32x32
      h = DDPMResnet(ch * self.ch_mult[-1], self.dropout_p)(h, time_embed=time_embed, train=train)
      h = SelfAttention(num_groups=8)(h)
      h = DDPMResnet(ch * self.ch_mult[-1], self.dropout_p)(h, time_embed=time_embed, train=train)



      # DECODING


      # 32x32
      for _ in range(self.n_resnet_blocks+1):
          h = DDPMResnet(ch*self.ch_mult[3], self.dropout_p)(jnp.concatenate([h, hs.pop()], axis = -1), time_embed=time_embed, train=train)
      B, H, W, C = h.shape
      h = jax.image.resize(h, (B, H*2, W*2, C), method='nearest')
      h = nn.Conv(ch * self.ch_mult[3], kernel_size=(3, 3), padding='CIRCULAR')(h)


      # 64x64
      for _ in range(self.n_resnet_blocks+1):
          h = DDPMResnet(ch*self.ch_mult[2], self.dropout_p)(jnp.concatenate([h, hs.pop()], axis = -1), time_embed=time_embed, train=train)
      B, H, W, C = h.shape
      h = jax.image.resize(h, (B, H*2, W*2, C), method='nearest')
      h = nn.Conv(ch * self.ch_mult[2], kernel_size=(3, 3), padding='CIRCULAR')(h)

      # 128x128
      for _ in range(self.n_resnet_blocks+1):
          h = DDPMResnet(ch*self.ch_mult[1], self.dropout_p)(jnp.concatenate([h, hs.pop()], axis = -1), time_embed=time_embed, train=train)
      B, H, W, C = h.shape
      h = jax.image.resize(h, (B, H*2, W*2, C), method='nearest')
      h = nn.Conv(ch * self.ch_mult[1], kernel_size=(3, 3), padding='CIRCULAR')(h)


      # level 0: 256x256, 64 filters
      for _ in range(self.n_resnet_blocks + 1):
          h = DDPMResnet(ch * self.ch_mult[0], self.dropout_p)(jnp.concatenate([h, hs.pop()], axis=-1), time_embed=time_embed, train=train)

      # output
      h = nn.GroupNorm(8)(h)
      h = jax.nn.silu(h)


      return nn.Conv(self.out_ch, kernel_size=(3, 3), padding='CIRCULAR')(h)

def build_samples(data, idx_list, mean, std):
    timesteps = np.arange(data.shape[1] - 2)
    samples = []
    for idx in idx_list:
        for t in timesteps:
            frame0 = (data[idx, t]   - mean) / std
            frame1 = (data[idx, t+1] - mean) / std
            frame2 = (data[idx, t+2] - mean) / std
            frame  = np.stack([frame0, frame1, frame2], axis=-1)
            samples.append(frame)
    return np.array(samples, dtype=np.float32)

def make_tf_ds(samples, batch_size):
    ds = tf.data.Dataset.from_tensor_slices(samples)
    ds = ds.shuffle(10000)
    ds = ds.batch(batch_size, drop_remainder=True)
    ds = ds.prefetch(tf.data.AUTOTUNE)
    return ds


def load_dataset(path, batch_size, stat_path=None, train_ratio=0.7):
    data = np.load(path)
    data = data[:8, :50, :, :]
    np.random.seed(1)
    indices = np.arange(data.shape[0])
    np.random.shuffle(indices)

    num_train_seeds = int(train_ratio * len(indices))
    num_val_seeds   = int(0.1 * len(indices))

    train_indices = indices[:num_train_seeds]
    val_indices   = indices[num_train_seeds:num_train_seeds + num_val_seeds]
    test_indices  = indices[num_train_seeds + num_val_seeds:]

    if stat_path is not None:
        stats = np.load(stat_path)
        mean  = stats['mean']
        std   = stats['std']
    else:
        train_data = data[train_indices]
        mean = np.mean(train_data)
        std  = np.std(train_data)

    train_ds = make_tf_ds(build_samples(data, train_indices, mean, std), batch_size)
    val_ds   = make_tf_ds(build_samples(data, val_indices,   mean, std), batch_size)
    test_ds  = make_tf_ds(build_samples(data, test_indices,  mean, std), batch_size)

    return train_ds, val_ds, test_ds, mean, std

# Calculate noise schedule
def calc_alpha(beta):
    alpha_bar = jnp.cumprod(1 - beta)
    return alpha_bar

# forward process, noising the image input
def forward_process(ims, t, alpha, eps):
    return jnp.sqrt(alpha[t])[:, None, None, None] * ims + jnp.sqrt(1 - alpha[t])[:, None, None, None] * eps

# Defining a train step, calculating the loss between actual noise and noise predicted by the unet.
@functools.partial(jax.jit, static_argnums=(1,6))
def train_step(params, model, ims, t, key, alpha_bar, train=True):

    def loss_fn(params):
        eps = jax.random.normal(key, ims.shape)
        noised_ims = forward_process(ims, t, alpha_bar, eps)

        if train:
            eps_pred = model.apply({'params': params}, noised_ims, t, train=train, rngs={'dropout': key})
        else:
            eps_pred = model.apply({'params': params}, noised_ims, t, train=train)
        return jnp.mean((eps - eps_pred)**2)

    if train:
        loss, grads = jax.value_and_grad(loss_fn)(params)
    else:
        loss = loss_fn(params)
        grads = None

    return loss, grads



# Implementing the sampling algorithm
def sample_step(model, params, dims, T, alpha_bar, beta_schedule, key):

    keys = jax.random.split(key, T+1)
    xT = jax.random.normal(keys[0], dims)

    for t in range(T, 0, -1):
        z = jax.random.normal(keys[t], xT.shape) if t > 1 else 0
        eps_pred = model.apply({'params': params}, xT, t, train=False)
        alpha_bar_t = alpha_bar[t]
        alpha_t = 1- beta_schedule[t]

        xt_bwd = (1/jnp.sqrt(alpha_t)) * (xT - (1-alpha_t)/jnp.sqrt(1-alpha_bar_t) * eps_pred) + jnp.sqrt(beta_schedule[t])*z

        xT = xt_bwd

    return xt_bwd


def plot_losses(train_losses, val_losses):
    clear_output(wait=True)
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.plot(train_losses, label='train')
    ax.plot(val_losses,   label='val')
    ax.set_xlabel('Epoch')
    ax.set_ylabel('MSE Loss')
    ax.set_title('DDPM Training')
    ax.legend()
    plt.tight_layout()
    plt.show()



# main training loop
def train_DDPM(n_epochs):
    batch_size = 32
    T = 1000
    beta_schedule = jnp.linspace(0.0001, 0.02, T)
    alpha_bar = calc_alpha(beta_schedule)

    key = jax.random.PRNGKey(0)

    # model init
    model = Unet(n_filters=128, dropout_p=0.1)
    key, init_key, dropout_key = jax.random.split(key, 3)
    dummy_x = jnp.ones((1, 256, 256, 3))
    dummy_t = jnp.ones((1,), dtype=jnp.int32)
    variables = model.init({"params": init_key, "dropout": dropout_key}, dummy_x, dummy_t)
    params = variables['params']

    # optimizer init
    optimizer = optax.adam(learning_rate=2e-4)
    opt_state = optimizer.init(params)

    # load dataset
    train_ds, val_ds, test_ds, mean, std = load_dataset(
        os.path.join(os.getcwd(), 'drive/MyDrive/colab/Thesis', 'kf_2d_re1000_256_40seed.npy'),
        batch_size
    )

    # Initialising empty loss lists
    train_loss = []
    val_loss = []

    epoch_bar = tqdm(range(n_epochs), desc='Epochs')


    for epoch in epoch_bar:

        epoch_train_loss = []
        train_bar = tqdm(enumerate(train_ds), desc=f'Train {epoch}/{len(epoch_bar)}', leave=False)
        for step, ims in train_bar:
            ims = jnp.array(ims.numpy())

            key, subkey1, subkey2 = jax.random.split(key, 3)
            t = jax.random.randint(subkey1, (batch_size,), minval=0, maxval=T)

            loss, grads = train_step(params, model, ims, t, subkey2, alpha_bar)

            updates, opt_state = optimizer.update(grads, opt_state)
            params = optax.apply_updates(params, updates)

            #if step % 100 == 0:
            #    print(f'Epoch {epoch}, step {step}, loss: {loss:.4f}')

            epoch_train_loss.append(loss)
            train_bar.set_postfix({'loss': f'{float(loss):.4f}'})

        train_loss.append(jnp.mean(epoch_train_loss))

        epoch_val_loss = []
        val_bar = tqdm(val_ds, desc=f'  Val   {epoch}', leave=False)
        for val_ims in val_bar:
            val_ims = jnp.array(val_ims.numpy())

            key, time_key, noise_key = jax.random.split(key, 3)

            t = jax.random.randint(time_key, (batch_size,), minval=0, maxval=T)

            loss, _ = train_step(params, model, val_ims, t, noise_key, alpha_bar, train=False)
            epoch_val_loss.append(loss)
            val_bar.set_postfix({'loss': f'{float(loss):.4f}'})

        val_loss.append(jnp.mean(epoch_val_loss))

        # update epoch bar with averages
        epoch_bar.set_postfix({
            'train': f'{train_loss[-1]:.4f}',
            'val':   f'{val_loss[-1]:.4f}'
        })

        # dynamic plot - updates every epoch
        plot_losses(train_loss, val_loss)

    return params, train_loss, val_loss

n_epochs = 300

train_ds, val_ds, test_ds, mean, std = load_dataset(os.path.join(os.getcwd(), 'drive/MyDrive/colab/Thesis', 'kf_2d_re1000_256_40seed.npy'),32)

for batch in train_ds:
    images = jnp.array(batch.numpy())
    print(images.shape)
    break

import matplotlib.pyplot as plt

for batch in train_ds:
    images = jnp.array(batch)  # no transpose needed
    print(images.shape)        # should be (32, 256, 256, 3)

    # plot the middle channel (current timestep) of first sample
    plt.imshow(images[0, :, :, 1], cmap='RdBu')
    plt.colorbar()
    plt.title('Channel 1 (middle timestep)')
    plt.show()
    break

jax.devices()

params, train_loss, val_loss = train_DDPM(n_epochs)