model:
  ch: 64
  ch_mult: [1, 1, 1, 2]
  out_ch: 3
  in_ch: 3
  n_resnet_blocks: 1
  dropout_p: 0.0
  freq_dim: 128

diffusion:
  T: 1000
  beta_start: 0.0001
  beta_end: 0.02

training:
  batch_size: 32
  learning_rate: 0.0002
  n_epochs: 300
  train_ratio: 0.7
  seed: 0

data:
  seeds_subset: 8
  timesteps_subset: 50
  image_size: 256
  gcs_bucket: ddpm-thesis-rh
  data_path: gs://ddpm-thesis-rh/flow-data/kf_2d_re1000_256_40seed.npy

checkpointing:
  save_every_n_epochs: 10
  checkpoint_dir: checkpoints/ddpm
